package exceptions;

public class IllegalAccessExceptions {

//		static void fun() throws IllegalAccessException  
//		{ 
//			//System.out.println("Inside the function"); 
//			throw new IllegalAccessException("Illegal Exception"); 
//		} 
//		
//		public static void main(String args[]) 
//		{ 
//			try
//			{ 
//				fun();
//			} 
//			catch(Exception e) 
//			{ 
//				System.out.println(e);
//			}
//		}
	
	public  static void main(String args[])
	{
		eg e=new eg();
		e.show(21);
	}
	
}
